---
startConfig:
  commandPrefix: a@ # Your bot's prefix to use for commands.
  commandEditableDuration: '30' # The amount of time before a command cannot be edited. (Only ping supports this right now.)
  nonCommandEditable: false # Whether commands can be edited after they have been executed.
  unknownCommandResponse: false # Whether to send a if a command is invalid.
  owner: # The list of owners.
  - '196443959558406144'
  - '253291447137075211'
  invite: http://discord.gg/Y6Vgfyd # The server invite to the support server.
loginConfig:
  token: token # Your bot's login token, keep this safe!
shardConfig:
  totalShards: 2 # The amount of shards to spawn when running the bot in a sharded mode.
  respawn: true # Whether shards should respawn if they close.
webhookConfig:
  webhookID: id # The webhook ID.
  webhookToken: token # The webhook token.
  enabled: false # Whether webhook events should be enabled or not.
  clientEvents:
    commandBlocked: false
    commandError: false
    commandPrefixChange: false
    commandRegister: false
    commandReregister: false
    commandRun: false
    commandStatusChange: false
    commandUnregister: false
    disconnect: false
    error: false
    groupRegister: false
    groupStatusChange: false
    guildCreate: false
    guildDelete: false
    rateLimit: false
    ready: false
    reconnecting: false
    typeRegister: false
    warn: false
  processEvents:
    uncaughtException: false
    unhandledRejection: false
    warning: false
  blacklistEvents:
    blacklistAdd: false
    blacklistRemove: false
