---
webhookID: '379795992012390411' # The webhook ID.
webhookToken: 'BXADXivdzppG8L4MuIc39_ASatdRjONZA7BoXikjv45yD817Ocz70gOUYi31sPxniMsI' # The webhook token.
enabled: true # Whether webhook events should be enabled or not.
clientEvents: # Enable and disable individual events.
  commandBlocked: true
  commandError: true
  commandPrefixChange: true
  commandRegister: true
  commandReregister: true
  commandRun: true
  commandStatusChange: true
  commandUnregister: true
  disconnect: true
  error: true
  groupRegister: true
  groupStatusChange: true
  guildCreate: true
  guildDelete: true
  rateLimit: true
  ready: true
  reconnecting: true
  typeRegister: true
  warn: true
processEvents:
  uncaughtException: true
  unhandledRejection: true
  warning: true
blacklistEvents:
  blacklistAdd: true
  blacklistRemove: true
